// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: proto/vision/v1/vision.proto

package visionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageUri      string                 `protobuf:"bytes,3,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Tasks         []*AnalysisTask        `protobuf:"bytes,6,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Params        map[string]string      `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeImageRequest) Reset() {
	*x = AnalyzeImageRequest{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImageRequest) ProtoMessage() {}

func (x *AnalyzeImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImageRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeImageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *AnalyzeImageRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *AnalyzeImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzeImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AnalyzeImageRequest) GetTasks() []*AnalysisTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *AnalyzeImageRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AnalysisTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisTask) Reset() {
	*x = AnalysisTask{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisTask) ProtoMessage() {}

func (x *AnalysisTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisTask.ProtoReflect.Descriptor instead.
func (*AnalysisTask) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnalysisTask) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AnalyzeImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Outputs       []*AnalysisOutput      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeImageResponse) Reset() {
	*x = AnalyzeImageResponse{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeImageResponse) ProtoMessage() {}

func (x *AnalyzeImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeImageResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeImageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *AnalyzeImageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnalyzeImageResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AnalyzeImageResponse) GetOutputs() []*AnalysisOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type AnalysisOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Classification *ClassificationResult  `protobuf:"bytes,2,opt,name=classification,proto3" json:"classification,omitempty"`
	Detection      *DetectionResult       `protobuf:"bytes,3,opt,name=detection,proto3" json:"detection,omitempty"`
	ProcessedImage *ProcessedImageResult  `protobuf:"bytes,4,opt,name=processed_image,json=processedImage,proto3" json:"processed_image,omitempty"`
	Text           *TextResult            `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Custom         map[string]string      `protobuf:"bytes,100,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalysisOutput) Reset() {
	*x = AnalysisOutput{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisOutput) ProtoMessage() {}

func (x *AnalysisOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisOutput.ProtoReflect.Descriptor instead.
func (*AnalysisOutput) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisOutput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnalysisOutput) GetClassification() *ClassificationResult {
	if x != nil {
		return x.Classification
	}
	return nil
}

func (x *AnalysisOutput) GetDetection() *DetectionResult {
	if x != nil {
		return x.Detection
	}
	return nil
}

func (x *AnalysisOutput) GetProcessedImage() *ProcessedImageResult {
	if x != nil {
		return x.ProcessedImage
	}
	return nil
}

func (x *AnalysisOutput) GetText() *TextResult {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *AnalysisOutput) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

type ClassificationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []*Label               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationResult) Reset() {
	*x = ClassificationResult{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationResult) ProtoMessage() {}

func (x *ClassificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationResult.ProtoReflect.Descriptor instead.
func (*ClassificationResult) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{4}
}

func (x *ClassificationResult) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{5}
}

func (x *Label) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Label) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type DetectionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detections    []*Detection           `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResult) Reset() {
	*x = DetectionResult{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResult) ProtoMessage() {}

func (x *DetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResult.ProtoReflect.Descriptor instead.
func (*DetectionResult) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{6}
}

func (x *DetectionResult) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Box           *BoundingBox           `protobuf:"bytes,3,opt,name=box,proto3" json:"box,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{7}
}

func (x *Detection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Detection) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetBox() *BoundingBox {
	if x != nil {
		return x.Box
	}
	return nil
}

type BoundingBox struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	X              float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y              float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Width          float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height         float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	CoordinateType string                 `protobuf:"bytes,5,opt,name=coordinate_type,json=coordinateType,proto3" json:"coordinate_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{8}
}

func (x *BoundingBox) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoundingBox) GetCoordinateType() string {
	if x != nil {
		return x.CoordinateType
	}
	return ""
}

type ProcessedImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedImageResult) Reset() {
	*x = ProcessedImageResult{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedImageResult) ProtoMessage() {}

func (x *ProcessedImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedImageResult.ProtoReflect.Descriptor instead.
func (*ProcessedImageResult) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessedImageResult) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ProcessedImageResult) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProcessedImageResult) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

type TextResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResult) Reset() {
	*x = TextResult{}
	mi := &file_proto_vision_v1_vision_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResult) ProtoMessage() {}

func (x *TextResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_v1_vision_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResult.ProtoReflect.Descriptor instead.
func (*TextResult) Descriptor() ([]byte, []int) {
	return file_proto_vision_v1_vision_proto_rawDescGZIP(), []int{10}
}

func (x *TextResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_vision_v1_vision_proto protoreflect.FileDescriptor

const file_proto_vision_v1_vision_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/vision/v1/vision.proto\x12\tvision.v1\"\xd9\x02\n" +
	"\x13AnalyzeImageRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x1b\n" +
	"\timage_uri\x18\x03 \x01(\tR\bimageUri\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12-\n" +
	"\x05tasks\x18\x06 \x03(\v2\x17.vision.v1.AnalysisTaskR\x05tasks\x12B\n" +
	"\x06params\x18\a \x03(\v2*.vision.v1.AnalyzeImageRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\fAnalysisTask\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12;\n" +
	"\x06params\x18\x02 \x03(\v2#.vision.v1.AnalysisTask.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\x14AnalyzeImageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x123\n" +
	"\aoutputs\x18\x05 \x03(\v2\x19.vision.v1.AnalysisOutputR\aoutputs\"\x96\x03\n" +
	"\x0eAnalysisOutput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12G\n" +
	"\x0eclassification\x18\x02 \x01(\v2\x1f.vision.v1.ClassificationResultR\x0eclassification\x128\n" +
	"\tdetection\x18\x03 \x01(\v2\x1a.vision.v1.DetectionResultR\tdetection\x12H\n" +
	"\x0fprocessed_image\x18\x04 \x01(\v2\x1f.vision.v1.ProcessedImageResultR\x0eprocessedImage\x12)\n" +
	"\x04text\x18\x05 \x01(\v2\x15.vision.v1.TextResultR\x04text\x12=\n" +
	"\x06custom\x18d \x03(\v2%.vision.v1.AnalysisOutput.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x14ClassificationResult\x12(\n" +
	"\x06labels\x18\x01 \x03(\v2\x10.vision.v1.LabelR\x06labels\"9\n" +
	"\x05Label\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\"G\n" +
	"\x0fDetectionResult\x124\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2\x14.vision.v1.DetectionR\n" +
	"detections\"k\n" +
	"\tDetection\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12(\n" +
	"\x03box\x18\x03 \x01(\v2\x16.vision.v1.BoundingBoxR\x03box\"\x80\x01\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\x12'\n" +
	"\x0fcoordinate_type\x18\x05 \x01(\tR\x0ecoordinateType\"l\n" +
	"\x14ProcessedImageResult\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\" \n" +
	"\n" +
	"TextResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2h\n" +
	"\x15VisionAnalysisService\x12O\n" +
	"\fAnalyzeImage\x12\x1e.vision.v1.AnalyzeImageRequest\x1a\x1f.vision.v1.AnalyzeImageResponseB0Z.iot-vision-platform/internal/visionpb;visionpbb\x06proto3"

var (
	file_proto_vision_v1_vision_proto_rawDescOnce sync.Once
	file_proto_vision_v1_vision_proto_rawDescData []byte
)

func file_proto_vision_v1_vision_proto_rawDescGZIP() []byte {
	file_proto_vision_v1_vision_proto_rawDescOnce.Do(func() {
		file_proto_vision_v1_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vision_v1_vision_proto_rawDesc), len(file_proto_vision_v1_vision_proto_rawDesc)))
	})
	return file_proto_vision_v1_vision_proto_rawDescData
}

var file_proto_vision_v1_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_vision_v1_vision_proto_goTypes = []any{
	(*AnalyzeImageRequest)(nil),  // 0: vision.v1.AnalyzeImageRequest
	(*AnalysisTask)(nil),         // 1: vision.v1.AnalysisTask
	(*AnalyzeImageResponse)(nil), // 2: vision.v1.AnalyzeImageResponse
	(*AnalysisOutput)(nil),       // 3: vision.v1.AnalysisOutput
	(*ClassificationResult)(nil), // 4: vision.v1.ClassificationResult
	(*Label)(nil),                // 5: vision.v1.Label
	(*DetectionResult)(nil),      // 6: vision.v1.DetectionResult
	(*Detection)(nil),            // 7: vision.v1.Detection
	(*BoundingBox)(nil),          // 8: vision.v1.BoundingBox
	(*ProcessedImageResult)(nil), // 9: vision.v1.ProcessedImageResult
	(*TextResult)(nil),           // 10: vision.v1.TextResult
	nil,                          // 11: vision.v1.AnalyzeImageRequest.ParamsEntry
	nil,                          // 12: vision.v1.AnalysisTask.ParamsEntry
	nil,                          // 13: vision.v1.AnalysisOutput.CustomEntry
}
var file_proto_vision_v1_vision_proto_depIdxs = []int32{
	1,  // 0: vision.v1.AnalyzeImageRequest.tasks:type_name -> vision.v1.AnalysisTask
	11, // 1: vision.v1.AnalyzeImageRequest.params:type_name -> vision.v1.AnalyzeImageRequest.ParamsEntry
	12, // 2: vision.v1.AnalysisTask.params:type_name -> vision.v1.AnalysisTask.ParamsEntry
	3,  // 3: vision.v1.AnalyzeImageResponse.outputs:type_name -> vision.v1.AnalysisOutput
	4,  // 4: vision.v1.AnalysisOutput.classification:type_name -> vision.v1.ClassificationResult
	6,  // 5: vision.v1.AnalysisOutput.detection:type_name -> vision.v1.DetectionResult
	9,  // 6: vision.v1.AnalysisOutput.processed_image:type_name -> vision.v1.ProcessedImageResult
	10, // 7: vision.v1.AnalysisOutput.text:type_name -> vision.v1.TextResult
	13, // 8: vision.v1.AnalysisOutput.custom:type_name -> vision.v1.AnalysisOutput.CustomEntry
	5,  // 9: vision.v1.ClassificationResult.labels:type_name -> vision.v1.Label
	7,  // 10: vision.v1.DetectionResult.detections:type_name -> vision.v1.Detection
	8,  // 11: vision.v1.Detection.box:type_name -> vision.v1.BoundingBox
	0,  // 12: vision.v1.VisionAnalysisService.AnalyzeImage:input_type -> vision.v1.AnalyzeImageRequest
	2,  // 13: vision.v1.VisionAnalysisService.AnalyzeImage:output_type -> vision.v1.AnalyzeImageResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_vision_v1_vision_proto_init() }
func file_proto_vision_v1_vision_proto_init() {
	if File_proto_vision_v1_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vision_v1_vision_proto_rawDesc), len(file_proto_vision_v1_vision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vision_v1_vision_proto_goTypes,
		DependencyIndexes: file_proto_vision_v1_vision_proto_depIdxs,
		MessageInfos:      file_proto_vision_v1_vision_proto_msgTypes,
	}.Build()
	File_proto_vision_v1_vision_proto = out.File
	file_proto_vision_v1_vision_proto_goTypes = nil
	file_proto_vision_v1_vision_proto_depIdxs = nil
}
