// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc2
// source: proto/vision/v1/vision.proto

package visionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisionAnalysisService_AnalyzeImage_FullMethodName = "/vision.v1.VisionAnalysisService/AnalyzeImage"
)

// VisionAnalysisServiceClient is the client API for VisionAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisionAnalysisServiceClient interface {
	AnalyzeImage(ctx context.Context, in *AnalyzeImageRequest, opts ...grpc.CallOption) (*AnalyzeImageResponse, error)
}

type visionAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisionAnalysisServiceClient(cc grpc.ClientConnInterface) VisionAnalysisServiceClient {
	return &visionAnalysisServiceClient{cc}
}

func (c *visionAnalysisServiceClient) AnalyzeImage(ctx context.Context, in *AnalyzeImageRequest, opts ...grpc.CallOption) (*AnalyzeImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeImageResponse)
	err := c.cc.Invoke(ctx, VisionAnalysisService_AnalyzeImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisionAnalysisServiceServer is the server API for VisionAnalysisService service.
// All implementations must embed UnimplementedVisionAnalysisServiceServer
// for forward compatibility.
type VisionAnalysisServiceServer interface {
	AnalyzeImage(context.Context, *AnalyzeImageRequest) (*AnalyzeImageResponse, error)
	mustEmbedUnimplementedVisionAnalysisServiceServer()
}

// UnimplementedVisionAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisionAnalysisServiceServer struct{}

func (UnimplementedVisionAnalysisServiceServer) AnalyzeImage(context.Context, *AnalyzeImageRequest) (*AnalyzeImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeImage not implemented")
}
func (UnimplementedVisionAnalysisServiceServer) mustEmbedUnimplementedVisionAnalysisServiceServer() {}
func (UnimplementedVisionAnalysisServiceServer) testEmbeddedByValue()                               {}

// UnsafeVisionAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisionAnalysisServiceServer will
// result in compilation errors.
type UnsafeVisionAnalysisServiceServer interface {
	mustEmbedUnimplementedVisionAnalysisServiceServer()
}

func RegisterVisionAnalysisServiceServer(s grpc.ServiceRegistrar, srv VisionAnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedVisionAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisionAnalysisService_ServiceDesc, srv)
}

func _VisionAnalysisService_AnalyzeImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionAnalysisServiceServer).AnalyzeImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisionAnalysisService_AnalyzeImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionAnalysisServiceServer).AnalyzeImage(ctx, req.(*AnalyzeImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisionAnalysisService_ServiceDesc is the grpc.ServiceDesc for VisionAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisionAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vision.v1.VisionAnalysisService",
	HandlerType: (*VisionAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeImage",
			Handler:    _VisionAnalysisService_AnalyzeImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vision/v1/vision.proto",
}
